version: "3"

tasks:
  default:
    desc: List the available tasks
    cmds:
      - task -l

  model:
    desc: Generate the dataclasses from the OAI-PMH XML Schema (XSD)
    cmds:
      - curl -O https://www.openarchives.org/OAI/2.0/OAI-PMH.xsd
      - poetry run xsdata generate OAI-PMH.xsd --package wapmh.model

  serve:
    desc: Run the OAI-PMH Repository in a development server
    cmds:
      - poetry run uvicorn wapmh.repository:app

  serve:dev:
    desc: Run the OAI-PMH Repository in a development server
    cmds:
      - poetry run fastapi dev wapmh/repository.py

  test:
    desc: Run the pytest tests
    env:
      PYTHONPATH: .
    cmds:
      - poetry run pytest

  container:run:
    desc: Run the OCI container
    cmds:
      - |
        podman run --rm -d -p 8080:8080 \
          -v ./example/queries/:/data/queries:z \
          -e QUERY_PATH="/data/queries" \
          -e SPARQL_ENDPOINT="http://localhost:5000/" \
          -e ADMIN_EMAILS='["you@example.org"]' \
          ghcr.io/deutsche-nationalbibliothek/wapmh:main