prefix dc: <http://purl.org/dc/elements/1.1/>
prefix lv: <http://purl.org/lobid/lv#>

select ?identifier ?datestamp {
    ?resourceIri a lv:ArchivedWebPage ;
        dc:identifier ?identifier .
    filter(substr(?identifier, 1, 1) != "(")
}