prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix lv: <http://purl.org/lobid/lv#>

select ?identifier ?datestamp {
    ?resourceIri a lv:ArchivedWebPage ;
        dc:date ?datestamp ;
        dc:identifier ?identifier .
    filter(!bound(?from) || ?datestamp >= xsd:dateTime(concat(?from, "T00:00:00Z")))
    filter(!bound(?until) || ?datestamp <= xsd:dateTime(concat(?until, "T00:00:00Z")))
    filter(substr(?identifier, 1, 1) != "(")
}